dales_root: /data/moussabendjilali/archive/data/dales_2
gt_root: data/dales_high_res
crop_size_m: 100.0
crop_stride_m: 100.0

voxel_size_levels: {
  "256": 0.4,
  "128": 0.8,
  "64": 1.6
  }

voxel_size_initial: 0.2
initial_size: 256
targets: [128, 64]

ground_class: 1
n_classes: 8

min_points_per_crop: 500
device: cuda
